apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-a2a-mcp
  namespace: xyz
  labels:
    app: xyz-a2a-mcp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xyz-a2a-mcp
  template:
    metadata:
      name: xyz-a2a-mcp
      labels:
        app: xyz-a2a-mcp
      annotations:
        prometheus.io/scrape: "true"
        fluentd.io/log: "true"
    spec:
      containers:
        - name: xyz-a2a-mcp
          image: 891377017161.dkr.ecr.eu-west-2.amazonaws.com/xyz-a2a-mcp:${GIT_COMMIT_ID}
          ports:
            - containerPort: 10254
              protocol: TCP
          env:
            - name: ENV
              value: "${ENV}"
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - "nc -z localhost 10254"
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
            - weight: 50
              podAffinityTerm:
                topologyKey: kubernetes.io/zone
      restartPolicy: Always

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
---
apiVersion: v1
kind: Service
metadata:
  name: xyz-a2a-mcp-service
  namespace: xyz
spec:
  selector:
    app: xyz-a2a-mcp
  ports:
  - name: xyz-a2a-mcp-port-10254
    protocol: TCP
    port: 10254
    targetPort: 10254
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
